name: JUnit Test Report

on:
  push:
    paths:
      - 'LOGS/**/*.JUNIT.XML'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  render-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render regression tests
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: 'Regression Tests'
          path: 'LOGS/TEST/*.JUNIT.XML'
          reporter: java-junit
          fail-on-error: false
          list-suites: all
          list-tests: all
          list-files: none
          collapsed: never

      - name: Render hardware compliance tests
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: 'Hardware Compliance Tests'
          path: 'LOGS/HWC/*.JUNIT.XML'
          reporter: java-junit
          fail-on-error: false
          list-suites: all
          list-tests: all
          list-files: none
          collapsed: never
